### ISSUE TITLE
Sonarr/Radarr setup not functional with certain docker images

### ISSUE THREAD

**Issue by Tr4il** [MediaButler/CLI-Linux#1] opened 2019-11-02 23:03 UTC
Hi!
I was trying to setup my sonarr/radarr with MediaButler but couldn't get through the setup with this CLI. I did some digging and found why.

When the script checks the domain and api key to verify that it's working, it looks for (in sonarr's case) for sonarr or nzbdrone with grep. Except with the docker image that I'm using to run sonarr, it's not mentioned in the http response body. So the script can't verify that it's actually talking to and receiving a correct response from Sonarr, and the setup fails. This is what comes back on a curl to the system status api:

`{
  "version": "3.0.3.652",
  "buildTime": "2019-10-20T20:17:31Z",
  "isDebug": false,
  "isProduction": true,
  "isAdmin": false,
  "isUserInteractive": false,
  "startupPath": "/app/bin",
  "appData": "/config/app",
  "osName": "ubuntu",
  "osVersion": "18.04",
  "isMonoRuntime": true,
  "isMono": true,
  "isLinux": true,
  "isOsx": false,
  "isWindows": false,
  "branch": "master",
  "authentication": "forms",
  "sqliteVersion": "3.22.0",
  "urlBase": "",
  "runtimeVersion": "5.20.1.19",
  "runtimeName": "mono"
}%  `

As you can see, there is no mention of sonarr in the response body (or radarr or nzbdrone for that matter).
This example is using the hotio/sonarr3 image, and hotio/radarr for radarr.
The Windows CLI fails in the exact same way.

I hope you see what I mean with this explanation, if not just hit me up.
If I find some time in the coming days, you might see a pull request proposing a fix (can't be that difficylt can it) but maybe you'd like to fix it in line with other examples.
I'd be glad to help with anything.

Thank you.

**Comment by tronyx** [comment] 2020-03-03 11:55
Not sure why I never got an e-mail notification about this, but yes, it is a problem, and one that, obviously, is not that easy to solve as I did not receive a PR from you *wink*. I will see what I can come up with in the next few days, if anything.

**Comment by grostim** [comment] 2020-04-26 16:19
I'll follow up this issue. 
For the time being mediabutler is unusable with cloudbox.

**Comment by tronyx** [comment] 2020-04-26 16:59
> 
> 
> I'll follow up this issue.
> For the time being mediabutler is unusable with cloudbox.

Ok, my apologies for that, but that doesn't change the fact that I haven't had to time to improve upon the existing process. I will fix it when I can.

**Comment by tronyx** [comment] 2020-04-26 19:22
@Tr4il @grostim Please try the latest version of the script from the develop branch: https://github.com/MediaButler/CLI-Linux/tree/develop

The fix checks to see if any backups exist, which are created automatically, as they have sonarr and radarr in the names.

**Comment by grostim** [comment] 2020-04-27 05:59
> > I'll follow up this issue.
> > For the time being mediabutler is unusable with cloudbox.
> 
> Ok, my apologies for that, but that doesn't change the fact that I haven't had to time to improve upon the existing process. I will fix it when I can.

Don't worry. I was not pointing my finger to anyone. Keep up the good work !



> @Tr4il @grostim Please try the latest version of the script from the develop branch: https://github.com/MediaButler/CLI-Linux/tree/develop
> 
> The fix checks to see if any backups exist, which are created automatically, as they have sonarr and radarr in the names.

I am using docker image. What would be the easiest way to update its content to the develop branch ?

**Comment by tronyx** [comment] 2020-04-28 14:40
@grostim You can pull the appropriate image for the System your CB is installed on from this list:

```
reg.mediabutler.app/mediabutler/linux-cli-utility:amd64-devel
reg.mediabutler.app/mediabutler/linux-cli-utility:arm32v6-devel
reg.mediabutler.app/mediabutler/linux-cli-utility:arm32v7-devel
reg.mediabutler.app/mediabutler/linux-cli-utility:arm64v8-devel
reg.mediabutler.app/mediabutler/linux-cli-utility:i386-devel
```

**Comment by tronyx** [comment] 2020-05-01 20:44
@grostim @Tr4il Have either of you had a moment to test this? Would like to get the change merged to the master branch and get this issue closed.

**Comment by grostim** [comment] 2020-05-01 21:28
Hi !

I tried it today.

I run a fresh install of the develop branch:
```
cloudbox@cloudbox:/opt/scripts/mediabutler-cli$ ./mb-linux-cli-utility.sh 
You didn't run the script as root!
Doing it for you now...

Welcome to the MediaButler Linux CLI Utility!

First thing we need to get started are your Plex credentials.
Please choose from one of the following options:

  1) Plex Username & Password
  2) Plex Auth Token
  3) Exit

Selection: 2

Please enter your Plex token:

Now we're going to make sure you provided valid credentials...
Success!

Please choose which Plex Server you would like to setup MediaButler for:

  1) REDACTED
  2) Cancel

Server: 1

Gathering required information...
Done!

Is this the correct MediaButler URL?
https://mediabutler.REDACTED.com/

[Y]es or [N]o:
Y

+---------------------------------------+
|              ~Main Menu~              |
+---------------------------------------+
Please select from the following options:
        (* indicates Admin only)         

  1) Configure Applications*
  2) Configure Permissions*
  3) Plex Media Requests
  4) Plex Media Issues
  5) Plex Playback Information
  6) Plex Library Information
  7) Plex Media Search
  8) Reset Configuration
  9) Exit

Selection: 1

+---------------------------------------+
|     ~Endpoint Configuration Menu~     |
+---------------------------------------+
Please choose which application you would
   like to configure for MediaButler:    

  1) Sonarr
  2) Radarr
  3) Tautulli
  4) Requests
  5) Back to Main Menu

Selection: 1

+---------------------------------------+
|          ~Sonarr Setup Menu~          |
+---------------------------------------+
Please choose which version of Sonarr you
would like to configure for MediaButler: 

  1) Sonarr
  2) Sonarr 4K
  3) Back to Endpoint Menu

Selection: 1

Please enter your Sonarr URL (IE: http://127.0.0.1:8989/sonarr/):
http://sonarr:8989

Please enter your Sonarr API key:

Testing that the provided Sonarr URL and API Key are valid...
cloudbox@cloudbox:/opt/scripts/mediabutler-cli$ 
```
At this point, i have been kicked out of the script without any error message.
I am not sure what is going wrong.

If i try to re-run the script, i have the following error:
```
cloudbox@cloudbox:/opt/scripts/mediabutler-cli$ ./mb-linux-cli-utility.sh 
You didn't run the script as root!
Doing it for you now...

jq: error: Could not open file /tmp/mb_setup/plex_creds_check.txt: No such file or directory
```

**Comment by tronyx** [comment] 2020-05-01 21:48
Ok, I will spin up a container using HotIO's image and see if I can encounter the same issue.

**Comment by tronyx** [comment] 2020-05-02 13:32
@grostim I see your issue. You're trying to use Docker DNS by specifying `http://sonarr:8989` and that won't work when you're just running the script. You would need to replace `sonarr` with the IP address of the Server running your Sonarr Docker container. You'll have to remove the `tmp/mb_setup/` directory and try again.

**Comment by grostim** [comment] 2020-05-03 12:32
> @grostim I see your issue. You're trying to use Docker DNS by specifying `http://sonarr:8989` and that won't work when you're just running the script. You would need to replace `sonarr` with the IP address of the Server running your Sonarr Docker container. You'll have to remove the `tmp/mb_setup/` directory and try again.

I'll try.
But i am not sure that using the IP is a good idea, as the IP may change next time docker will restart.

**Comment by grostim** [comment] 2020-05-03 12:41
Ok,
This works for sonarr.
But not for Radarr.
```

+---------------------------------------+
|     ~Endpoint Configuration Menu~     |
+---------------------------------------+
Please choose which application you would
   like to configure for MediaButler:

  1) Sonarr
  2) Radarr
  3) Tautulli
  4) Requests
  5) Back to Main Menu

Selection: 2

+---------------------------------------+
|          ~Radarr Setup Menu~          |
+---------------------------------------+
Please choose which version of Radarr you
would like to configure for MediaButler:

  1) Radarr
  2) Radarr 4K
  3) Radarr 3D
  4) Back to Endpoint Menu

Selection: 1

Please enter your Radarr URL (IE: http://127.0.0.1:7878/radarr/):
http://172.18.0.20:7878

Please enter your Radarr API key:

Testing that the provided Radarr URL and API Key are valid...
jq: error (at <stdin>:23): Cannot index string with string "name"
There was an error while attempting to validate the provided information!

```

Is it related with the fact i am using radarr:aphrodite ?

**Comment by grostim** [comment] 2020-05-03 12:44
And I still have the same error at the next execution :
```
 ./mb-linux-cli-utility.sh
You didn't run the script as root!
Doing it for you now...

jq: error: Could not open file /tmp/mb_setup/plex_creds_check.txt: No such file or directory
```
 the directory /tmp/mb_setup is empty.

**Comment by tronyx** [comment] 2020-05-03 13:28
> cloudbox@cloudbox:/opt/scripts/mediabutler-cli$ ./mb-linux-cli-utility.sh

Are you even using the Docker image? It doesn't look like it, so make sure you download the latest version of the script:

https://github.com/MediaButler/CLI-Linux/blob/master/mb-linux-cli-utility.sh

> I'll try.
> But i am not sure that using the IP is a good idea, as the IP may change next time docker will restart.

I said use the IP address of the Server, not the container.

> This works for sonarr.
> But not for Radarr.

Please make sure you're using the most recent version of the script as I put the same fix in for Radarr as I did for Sonarr. I am currently unable to reproduce the issue with either of HotIO's images for Sonarr or Radarr.

> And I still have the same error at the next execution

I'm still trying to track down a catch and fix for that last error.

**Comment by Tr4il** [comment] 2020-05-03 18:05
I got it to work with Sonarr now, which is great! But for Radarr i'm having the same issues as the guy above. Exactly that as well, so I did some digging. The version of the script that is now on the master branch still queries the radarr api asking for:

` radarrAppCheckResponse=$(curl -sL --connect-timeout 10 "${convertedURL}api/system/status" -H "X-Api-Key: ${radarrAPIKey}" | jq .[].name | grep -ci radarr)`

status!

While the Sonarr lines, of course, query for the backups:

`sonarrAppCheckResponse=$(curl -sL --connect-timeout 10 "${convertedURL}api/system/backup" -H "X-Api-Key: ${sonarrAPIKey}" | jq .[].name | grep -cEi 'sonarr')`

So, that's where the issue still is I guess? Maybe you didn't push the commit for the radarr lines?
Anyhow, thanks for fixing!

**Comment by tronyx** [comment] 2020-05-03 19:58
@Tr4il Whoops, my bad. I put the extra lines in, but never updated them from system to backup. I've made the change now and just pushed to master.

**Comment by tronyx** [comment] 2020-05-08 22:15
@Tr4il @grostim Hello? I would like to get this confirmed as fixed and merged.

**Comment by Tr4il** [comment] 2020-05-08 22:21
It seems to be working correctly now!
I'm sorry for the delay, my life has been a bit hectic the past few weeks.

**Comment by tronyx** [comment] 2020-05-09 23:50
No problem, @Tr4il. Thanks for confirming. I'm going to consider this closed.

**Closed as completed by tronyx** 2020-05-09 23:50 UTC
Labels: bug, help wanted
